### ISSUE TITLE
Error writing unicode character \u24e4 when creating default config file

### ISSUE THREAD

**Issue by xdhmoore** [dagraham/etm-dgraham#9]
I'm on windows 10. When I start etm for the first time, I get the error below. It seems to be choking up on the ⓤ character on line 92 of options.py. The cfg.yaml file that is partially written before failure appears to be in UTF-8, so I'm not sure why the stack trace seems to show a use of cp1252.

```
Traceback (most recent call last):
  File "C:\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\tools\etm\.venv\Scripts\etm.exe\__main__.py", line 7, in <module>
  File "d:\tools\etm\.venv\lib\site-packages\etm\__main__.py", line 38, in main
    settings = options.Settings(etmdir).settings
  File "d:\tools\etm\.venv\lib\site-packages\etm\options.py", line 334, in __init__
    yaml.dump(self.settings, fn)
  File "d:\tools\etm\.venv\lib\site-packages\ruamel\yaml\main.py", line 451, in dump
    return self.dump_all([data], stream, _kw, transform=transform)
  File "d:\tools\etm\.venv\lib\site-packages\ruamel\yaml\main.py", line 465, in dump_all
    self._context_manager.dump(data)
  File "d:\tools\etm\.venv\lib\site-packages\ruamel\yaml\main.py", line 817, in dump
    self._yaml.representer.represent(data)
  File "d:\tools\etm\.venv\lib\site-packages\ruamel\yaml\representer.py", line 86, in represent
    self.serializer.serialize(node)
  File "d:\tools\etm\.venv\lib\site-packages\ruamel\yaml\serializer.py", line 117, in serialize
    self.serialize_node(node, None, None)
  File "d:\tools\etm\.venv\lib\site-packages\ruamel\yaml\serializer.py", line 233, in serialize_node
    self.serialize_node(value, node, key)
  File "d:\tools\etm\.venv\lib\site-packages\ruamel\yaml\serializer.py", line 173, in serialize_node
    self.emitter.emit(
  File "d:\tools\etm\.venv\lib\site-packages\ruamel\yaml\emitter.py", line 254, in emit
    self.state()
  File "d:\tools\etm\.venv\lib\site-packages\ruamel\yaml\emitter.py", line 708, in expect_block_mapping_simple_value
    self.expect_node(mapping=True)
  File "d:\tools\etm\.venv\lib\site-packages\ruamel\yaml\emitter.py", line 422, in expect_node
    self.expect_scalar()
  File "d:\tools\etm\.venv\lib\site-packages\ruamel\yaml\emitter.py", line 470, in expect_scalar
    self.process_scalar()
  File "d:\tools\etm\.venv\lib\site-packages\ruamel\yaml\emitter.py", line 890, in process_scalar
    self.write_post_comment(self.event)
  File "d:\tools\etm\.venv\lib\site-packages\ruamel\yaml\emitter.py", line 1688, in write_post_comment
    self.write_comment(comment)
  File "d:\tools\etm\.venv\lib\site-packages\ruamel\yaml\emitter.py", line 1657, in write_comment
    self.stream.write(value)
  File "C:\Python38\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u24e4' in position 219: character maps to <undefined>
```

**Comment by dagraham** [comment]
Thanks for pointing this out. The problem, so far as I can tell, is that the windows console application you are using doesn't support this double-width unicode character. As a possible solution, I have replaced the instances of double width characters with single width alternatives in the version now available here on github. I do not have access to a windows machine so I cannot confirm this fix.  When you have a chance, would you try it out and let me know if it solves the problem for you?

Thanks

**Comment by xdhmoore** [comment]
The change didn't fix the problem for me, but I think I figured it out. In options.py, when  `open()` is used on line 332, on Windows it opens up the stream with cp1252 encoding by default. I think the fix is to explicitly tell `open()` to use `utf-8`. Like so:

```python
331        if self.changes:
332            with open(self.cfgfile, 'w', encoding='utf-8') as fn:
333               yaml.dump(self.settings, fn)
334            logger.info(f"updated {self.cfgfile}: {', '.join(self.changes)}")
```

I guess this probably applies to other places where `open()` is used as well. With that fixed, I'm also hitting an issue with line 1713 of model.py, `from time import clock as timer`. Maybe leftover python 2 code? I'll see if I can cobble together a PR within the next week or so.

**Comment by dagraham** [comment]
Many thanks. I'll look forward to your PR. Help with Windows is much appreciated!

**Comment by dagraham** [comment]
Inactive and presumably fixed.
